language: android
dist: trusty
sudo: required
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "ndk-bundle"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew

# Just build the project for now
script:
 - ./gradlew assembleAppDebug
 - find . -name '*.apk'

deploy:
  provider: releases
  file: "vector/build/outputs/apk/app/release/vector-app-universal-release-unsigned.apk" #"vector/build/outputs/apk/app/debug/vector-app-debug.apk"
  skip_cleanup: true
  draft: true
  on:
    branch: patch-1
  api_key:
    secure: "eYYS17LoICxHfQJGATxt2xiOWACCTxoV2hmeQW43BZZp5Qwy5dzi0A1wsAWor5fCK2+gz4ROKvUtdFoEssAmqyXccK9jknbV71UjMOuy039V3NnbFDFYCYL9b43PjPL+RTikZkVL6lUIhy/L3/qH1SjqPLovoZYCyW1odASHeq2wInisamr90j27AhSc/+tKgBuPAu/ul8lVygtHyZqgsa6eB9dkATvzSZI3TYbkdX++Mvv+iXIG+U32v8dW/GBhm6obRGrnJPHyEcGRtpENkPhBqx7AwyrxfaPCsKMgN6w70Jzb60QH5cP8kPRtxVAcdKQNB5XdRVjFV5W1ZI8NN7eztS1wqLAN/uMZevPfoGhW+05g1bMVSZgto1fOvJHSI11tqS/aeRXEOMFWxC45fBU2xu0FTuYRPemu5RmPcZSgYfvWcPXt0fFL7ZNO+E4+kFEJ2gUxfEx2a9d+lNJiQcTR8tn8lqxYPslPOyHXz/DYGWwcPTn9/sYWnCkoL+HOPoTNMp3Fp1xx50qplutEinllL/w/zSvpMGxqNhU4TgR6AaBtLC/pIasL6F80dFYdbmsvN05Dyd9BLPj5fAUIMnhkOoQAA0+ZIfR1u1SAwvCSow0lgQ52xSs+wFeI0G4F5Y+WuvjVdEcKtxC3K7no31rh7TVaSVyd5CngXiR+4Qk="
